Revert "!drop: tmp: Speed up CI w/ `Swatinem/rust-cache`"
Caching hit seems to be causing this new test failure for all platforms
```
 failures:

---- freshness::changing_bin_features_caches_targets stdout ----
error: test failed, to rerun pass `-p cargo --test testsuite`
running `/Users/runner/work/cargo/cargo/target/debug/cargo build`
thread 'freshness::changing_bin_features_caches_targets' panicked at tests/testsuite/freshness.rs:525:10:

test failed running `/Users/runner/work/cargo/cargo/target/debug/cargo build`
error: stderr did not match:
1        -tests/testsuite/freshness.rs:520:22
    1    +   Compiling foo v0.0.1 (/Users/runner/work/cargo/cargo/target/tmp/cit/t4/foo)
    2    +    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.75s
```
https://github.com/choznerol/cargo/actions/runs/9780417859/job/27002033639

This reverts commit 3b2dd166d280d3abbeeb3ccb7b3129ced9c0f551.