fixup! test(freshness): migrate to snapbox
Fix https://github.com/choznerol/cargo/pull/2#discussion_r1664378710

Full snapshot when running locally:
```
[DIRTY] foo v0.0.1 ([ROOT]/foo): the dependency foo was rebuilt ([TIME_DIFF_AFTER_LAST_BUILD])
[COMPILING] foo v0.0.1 ([ROOT]/foo)
[RUNNING] `rustc --crate-name foo --edition=2015 tests/foo.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked --test --check-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values())' -C metadata=f8f4b1ccd5eb53e0 -C extra-filename=-f8f4b1ccd5eb53e0 --out-dir [ROOT]/foo/target/debug/deps -L dependency=[ROOT]/foo/target/debug/deps --extern foo=[ROOT]/foo/target/debug/deps/libfoo-[HASH].rlib`
[RUNNING] `rustc --crate-name foo --edition=2015 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked --test --check-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values())' -C metadata=56205d785c25fa8c -C extra-filename=-56205d785c25fa8c --out-dir [ROOT]/foo/target/debug/deps -L dependency=[ROOT]/foo/target/debug/deps`
error[E0425]: cannot find function `foo` in crate `foo`
 --> tests/foo.rs:4:34
  |
4 |                 fn test() { foo::foo(); }
  |                                  ^^^ not found in `foo`

For more information about this error, try `rustc --explain E0425`.
[ERROR] could not compile `foo` (test "foo") due to 1 previous error

Caused by:
  process didn't exit successfully: `rustc --crate-name foo --edition=2015 tests/foo.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked --test --check-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values())' -C metadata=f8f4b1ccd5eb53e0 -C extra-filename=-f8f4b1ccd5eb53e0 --out-dir [ROOT]/foo/target/debug/deps -L dependency=[ROOT]/foo/target/debug/deps --extern foo=[ROOT]/foo/target/debug/deps/libfoo-[HASH].rlib` ([EXIT_STATUS]: 1)
[WARNING] build failed, waiting for other jobs to finish...
```

Turns out the `[WARNING]` line may not show every time. Matching the `[ERROR] could not compile ...` line is a better choice.